name: "build_iso"
on:
  workflow_dispatch:

jobs:
  build_iso:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: DeterminateSystems/nix-installer-action@v3
    - run: nix build .#images.thisismycomputernow
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: result
        path: |
          result/iso/*.iso